version: '3.8'

services:
  web:
    build: .
    ports:
      - "0.0.0.0:5000:5000"  # Changed this line
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MONGO_URI=mongodb://root:example@mongo:27017/auth_app?authSource=admin
    volumes:
      - .:/app
      - ./static:/app/static
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped

volumes:
  mongodb_data: